captureDirectory: 'C:/Videos/MFC' # Choose a directory for the recorded files
completeDirectory: 'C:/Videos/MFC' # Choose a directory for the complete recorded files
modelScanInterval: 30 # In seconds, how often mfc-node checks for newly online models
createModelDirectory: false # If you want all the files from same model be recorded in the separate subdirectory
dateFormat: DDMMYYYY-HHmmss # Choose date format for the filename, for example: YYYY-MM-DD_HH-mm-ss
downloadProgram: rtmp # Choose program for download stream (rtmp, sl, ls, ff-ts, ff-flv and hls)
minFileSizeMb: 0 # If you do not want to save a file smaller than 5 MB enter number 5
port: 8888 # number of port for your browser url for example: http://localhost:8888/
debug: true # If you want a more detailed view put 'true' or 'false' to skip this option
models: # This is only example - all your models will be added with your browser with spinner
  - uid: 18363406
    mode: 1
    nm: HOTREAL36DD
queue: []
#proxyServer: '97.72.74.166:87' # If you want to bypass region block use some good proxy server
#
#For windows users download links:
#http://www.mediafire.com/file/aim84bicrsbbvci/MFCD.rar/file
#http://www.mediafire.com/file/d9obqdq71cqeehr/hlsdl.exe/file
