captureDirectory: 'C:/Videos/MFC' # Choose a directory for the recorded files
createModelDirectory: true # If you want all the files from same model be recorded in the separate subdirectory
directoryFormat: id+nm # You can choose between 'id+nm','nm+id','id' and 'nm' separate subdirectory format (Of course only if the previous option is 'true')
dateFormat: DDMMYYYY-HHmmss # Choose date format for the filename, for example: YYYY-MM-DD_HH-mm-ss
downloadProgram: ls # You can choose between 'ls' for 'livestreamer' and 'sl' for 'streamlink'
fileFormat: mp4 # You can choose between 'mp4' and 'ts'
modelScanInterval: 30 # In seconds, how often mfc-node checks for newly online models
minFileSizeMb: 0 # If you do not want to save a file smaller than 5 MB enter number 5
port: 8888 # number of port for your browser url for example: http://localhost:8888/
debug: true # If you want a more detailed view put 'true' or 'false' to skip this option
models: # This is only example - models will be added with your browser
  - uid: 18363406
    mode: 1
    nm: HOTREAL36DD
queue: 
