captureDirectory: 'C:\Videos\MFC'
dateFormat: DDMMYYYY-HHmmss
modelScanInterval: 60
minFileSizeMb: 0
port: 9080
debug: true
models: []
includeModels: []
includeUids: []
excludeModels: []
excludeUids: []
deleteModels: []
deleteUids: []
